### PR TITLE
fix SQL statement for PostgreSQL

### PR DESCRIPTION
**Pull request by jurgens**

### CODE REVIEW

**Comment by jcoyne** [comment]
Please say more about this. Why is this necessary?

**Comment by jurgens** [comment]
unfortunately I can't find related issue - but I'm sure it was there.
The problem is with this latest commit https://github.com/mailboxer/mailboxer/commit/99d16871375c0a34097d1ef122a9e42fc918794c and the problem is that it does not work with PostgreSQL (I presume it was only tested with MySQL)

**Comment by kotay** [comment]
@jurgens, @jcoyne - This seems to fix the issue with this pull request: https://github.com/mailboxer/mailboxer/pull/397

**Comment by jcoyne** [comment]
Okay. Now we just need to fix the build. Do you want to remove Ruby 1.9 from the build matrix?

**Comment by mstedler** [comment]
any update on this?

**Comment by jurgens** [comment]
@mstedler @jcoyne done

**Comment by jcoyne** [comment]
@jurgens Can you set jruby as an allowed failure (or remove it altogether) and then I'd be happy to merge.

**Comment by jcoyne** [comment]
Superseded by #425

**Pull request closed without merging**
