### PR TITLE
Made the notification body encrypted in db using attr_encrypted. 

### PR DESCRIPTION
**Pull request by khurananick**
Thought it could be useful for everyone else. I wouldn't want just about anyone with access to db decipher what my users are talking about.

### CODE REVIEW

**Comment by jcoyne** [comment]
What's the migration strategy for this?

**Comment by khurananick** [comment]
Hey, not quite sure what you mean as I'm a noob when contributing to repos. Do you think it's better to create a new migration that changes the column name? Or are you referring to keeping it backwards compatible with some more logic that encrypts existing data?

**Comment by jcoyne** [comment]
What I'm saying is that many adopters have a database full of data. What happens when we apply your patch?  Is our data suddenly unreadable?  Does it raise errors?

**Comment by khurananick** [comment]
Got it. I'll go ahead and cancel this pull and submit a new patch that takes this into account.

**Pull request closed without merging**
