### PR TITLE
Allow messages without a subject

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Also fixes another problem that could happen during url generation in email templates.

### CODE REVIEW

**Comment by jcoyne** [comment]
Build is broken. Do you want to remove 1.9.3 from the matrix?

**Comment by deivid-rodriguez** [comment]
Sure, I updated it to be a bit more... "modern"

**Comment by deivid-rodriguez** [comment]
It passes now!

**Comment by jcoyne** [comment]
Thanks @deivid-rodriguez !

**Comment by deivid-rodriguez** [comment]
Thanks to you!

**Pull request merged**
