### PR TITLE
Get conversations between two messageable. Fix #389

### LINKED ISSUE #389: Finding a conversation by recipients
I have a controller action where I find a `Councillor`, and I need to find or create a conversation between the `current_user` and the `@councillor`.

So theoretically something like this:

```
@councillor = Councillor.find params[:id]
@conversation = current_user.mailbox.conversations.where(recipients: @councillor)
```

### PR DESCRIPTION
**Pull request by soyellupi**
It provides a way to find conversations between two participants

### CODE REVIEW

**Comment by kotay** [comment]
FYI: The `between` scope on the `Conversation` model is throwing a Postgres syntax error for me:

```
$> participant_1.mailbox.conversations_with(participant_2).first
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  subquery in FROM must have an alias
LINE 1: ..."conversations".* FROM "conversations" INNER JOIN (SELECT "m...
                                                             ^
HINT:  For example, FROM (SELECT ...) [AS] foo.
```

Can you replicate this behaviour on a Postgres DB?

**Comment by jurgens** [comment]
same for me
```
p.mailbox.conversations.between h, p
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  subquery in FROM must have an alias
LINE 1: ...n_id" = "mailboxer_notifications"."id" INNER JOIN (SELECT "m...
                                                             ^
HINT:  For example, FROM (SELECT ...) [AS] foo.
```

**Comment by kotay** [comment]
@jcoyne @soyellupi Has anyone else been able to replicate this?

**Comment by alagos** [comment]
For anyone with this issue, I fixed it forking the project and removing all the grave accents from the SQL query of [this scope](https://github.com/mailboxer/mailboxer/pull/397/files#diff-baa446efab01c00eeefe02723b1d75e0R35) (didn't started a PR as maybe my change will break compatibilty with another DB engine), so my copy looks like this:

```
  scope :between, lambda {|participant_one, participant_two|
    joins("INNER JOIN (#{Mailboxer::Notification.recipient(participant_two).to_sql}) participant_two_notifications ON participant_two_notifications.conversation_id = mailboxer_conversations.id AND participant_two_notifications.type IN ('Mailboxer::Message')").
        joins("INNER JOIN mailboxer_receipts ON mailboxer_receipts.notification_id = participant_two_notifications.id ").
        merge(Mailboxer::Receipt.recipient(participant_one)).
        order("mailboxer_conversations.updated_at DESC").uniq
  }

```

**Comment by soyellupi** [comment]
@alagos I confirm that your scope works right in MySQL

**Pull request merged**
