### PR TITLE
Relying on id in addition to the created_at timestamp to load entries chronologically

### PR DESCRIPTION
**Pull request by modsaid**
It happens of messages were created nearly instantly (in test cases for example) that they get the same  `created_at`,  which results in the wrong `conversation#last_message`.  taking the ID into consideration can be helpful if the created_at are for any reason equal

### CODE REVIEW

**Comment by rposborne** [comment]
Just a note, that created_at can easily have collisions on systems that don't support nanosecond timestamps in the DB.  We had a similar issue in paper trail gem awhile back with Mysql only supporting milliseconds.  

Just a use case to back up the addition of this. :)

**Comment by modsaid** [comment]
@jcoyne   do you think we can get this merged in?

**Comment by modsaid** [comment]
Thank you @rposborne

**Comment by modsaid** [comment]
closing this, as it is already handled in https://github.com/mailboxer/mailboxer/pull/441

**Pull request closed without merging**
