### PR TITLE
Rails 5 compatibility 

### PR DESCRIPTION
**Pull request by jeremymarc**

### CODE REVIEW

**Comment by jcoyne** [comment]
This appears to break compatibility with Rails 4.1, but it doesn't drop it from the .travis.yml build matrix.

**Comment by jeremymarc** [comment]
we could create a branch in that case

**Comment by jcoyne** [comment]
You *could*, but since Rails 4.1 will no longer be supported by Rails core, why should mailboxer support it?

**Comment by jeremymarc** [comment]
I don't undertand, my PR is to support Rails 5, not Rails 4.1

**Comment by jcoyne** [comment]
Yes, but you've broken the 4.1 builds in travis.  So, you should remove them, so we stop testing it on 4.1

**Comment by jeremymarc** [comment]
@jcoyne like this you mean?

**Comment by jcoyne** [comment]
Yes. You should probably add Rails 5 in there too.

**Comment by jcoyne** [comment]
You'll need to remove these lines too: https://github.com/jeremymarc/mailboxer/blob/5a915efc44915ca7c6a6fc0b310b2f0521add63c/.travis.yml#L9-L11

**Comment by jeremymarc** [comment]
done

**Comment by jcoyne** [comment]
@jeremymarc great, now we just need to add Rails 5 in there.

**Comment by jcoyne** [comment]
It appears the build with rails 5 is broken on Travis.

**Comment by atussec** [comment]
how can i use this branch?

**Comment by jcoyne** [comment]
Superseded by #423

**Pull request closed without merging**
